import type { StarlightUserConfig } from '@astrojs/starlight/types';

type Sidebar = NonNullable<StarlightUserConfig['sidebar']>;
type SidebarItem = Sidebar[number];

/**
 * Starlight strips `src/content/docs/` from entry `filePath` when building
 * autogenerated sidebar groups. With a root-level docs dir, `filePath` stays
 * like `docs/reference/example.md`, so autogenerate directories must be prefixed
 * with that docs dir for matching to succeed.
 *
 * When `sidebar` is omitted, autogenerate the entire docs tree from the
 * content collection (sections are filtered per-request in route middleware).
 */
export function adaptSidebarForDocsDir(
	sidebar: StarlightUserConfig['sidebar'],
	docsDir: string,
): Sidebar | undefined {
	const prefix = docsDir.replace(/\\/g, '/').replace(/\/+$/, '');

	if (!sidebar) {
		return [{ autogenerate: { directory: prefix } }];
	}

	return rewriteItems(sidebar, prefix);
}

function rewriteItems(items: SidebarItem[], prefix: string): SidebarItem[] {
	return items.map((item) => {
		if ('autogenerate' in item) {
			const dir = item.autogenerate.directory.replace(/\\/g, '/').replace(/^\/+|\/+$/g, '');
			const directory =
				dir === prefix || dir.startsWith(`${prefix}/`) ? dir : `${prefix}/${dir}`;
			return {
				...item,
				autogenerate: { ...item.autogenerate, directory },
			};
		}
		if ('items' in item) {
			return { ...item, items: rewriteItems(item.items, prefix) };
		}
		return item;
	});
}
